"""fix access control

Revision ID: 676b2a64cfda
Revises: d7cfd05374f3
Create Date: 2025-03-11 16:25:51.088938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676b2a64cfda'
down_revision = 'd7cfd05374f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder_user',
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('folder_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folder_user')
    # ### end Alembic commands ###
